name: RumBenPets
author: Skullex
OrigionalAuthor: Adam1609 & Justin
description: A fork of YaBoiBalAnce with an amazing support! Work with Genisys and Imagicalmine
version: 1.0.3 
main: RBC\Main
api: 2.0.0
